### ISSUE TITLE
Transaction ID

### ISSUE THREAD

**Issue by bojankostic81** [my-tribe/AppStoreServerApi#3]
Hi,

Thanks for the awesome library! Is there a way to extract the original transaction ID from a receipt?

**Comment by tarasov65536** [comment]
Hi,

Thank you for your kind words!

As for extracting the original transaction ID directly from a receipt, unfortunately I’m not aware of any reliable way to do this. Previously, Apple provided the [verifyReceipt ](https://developer.apple.com/documentation/appstorereceipts/verifyreceipt) endpoint which returned this information, but it is now deprecated and no longer recommended for use.

In my own projects, I don’t rely on [verifyReceipt ](https://developer.apple.com/documentation/appstorereceipts/verifyreceipt) anymore. Instead, we receive the **originalTransactionId** from the client-side app (using StoreKit 2), and then use that to query the App Store Server API from the backend.

**Comment by bojankostic81** [comment]
I'm using Unity IAP on the client side, which still works with receipts, but I managed to figure it out.

I have one more question regarding server notifications. I need to catch when the user cancels the subscription on their phone on the server side. As per the documentation, this should be done using a webhook endpoint where Apple will send this info. Do you have an example for this workflow?

**Comment by tarasov65536** [comment]
Hi! Yes, you're absolutely right — the way to catch subscription cancellations (and other lifecycle events) is via Apple’s App Store Server Notifications webhook.

Good news: as of version 1.0.0 of the [AppStoreServerApi](https://www.nuget.org/packages/MyTribe.AppStoreServerApi/1.0.0) library, I've added full support for handling [App Store Server Notifications](https://developer.apple.com/documentation/AppStoreServerNotifications).

You can now create a simple webhook endpoint in your server that receives and parses [ResponseBodyV2](https://github.com/my-tribe/AppStoreServerApi/blob/main/AppStoreServerApi/Models/ResponseBodyV2.cs) payloads. Here's a quick example in ASP.NET Core:
```csharp
[HttpPost("apple/v2")]
public IActionResult HandleAppleNotification([FromBody] ResponseBodyV2 notification)
{
    Console.WriteLine($"Received {notification.SignedPayload.DecodedPayload.NotificationType}");

    return Ok();
}
```

**Comment by bojankostic81** [comment]
Thanks!

In version 1.0.0, when I try to get all subscription statuses, like

`var response = await _client.GetAllSubscriptionStatusesAsync(transactionId);`

I receive an error:

Error checking subscription: The JSON value could not be converted to AppStoreServerApi.Models.Status. Path: $.data[0].lastTransactions[0].status | LineNumber: 0 | BytePositionInLine: 181.

**Comment by tarasov65536** [comment]
Thanks for reporting this!

The issue has been fixed, and a new version **1.0.2** is now available on NuGet. You can update to the latest version to resolve the JSON deserialization error when calling **GetAllSubscriptionStatusesAsync**.

Let me know if you run into anything else!

**Comment by bojankostic81** [comment]
Thank you for the quick action!

It seems that there is still an issue:

Stack overflow.
Repeated 19530 times: at AppStoreServerApi.Models.Status..ctor(Int32)
   at AppStoreServerApi.Models.Status.AppStoreServerApi.Json.IRawInt32<AppStoreServerApi.Models.Status>.FromRaw(Int32)
   at AppStoreServerApi.Json.RawInt32Converter`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Read(System.Text.Json.Utf8JsonReader ByRef, System.Type, System.Text.Json.JsonSerializerOptions)
   at System.Text.Json.Serialization.JsonConverter`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(System.Text.Json.Utf8JsonReader ByRef, System.Type, System.Text.Json.JsonSerializerOptions, System.Text.Json.ReadStack ByRef, System.__Canon ByRef, Boolean ByRef)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Text.Json.ReadStack ByRef, System.Text.Json.Utf8JsonReader ByRef, System.Text.Json.Serialization.Metadata.JsonParameterInfo, System.__Canon ByRef)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadAndCacheConstructorArgument(System.Text.Json.ReadStack ByRef, System.Text.Json.Utf8JsonReader ByRef, System.Text.Json.Serialization.Metadata.JsonParameterInfo)

**Comment by bojankostic81** [comment]
Hi, any news on this issue?

**Comment by tarasov65536** [comment]
Thanks again for the follow-up!

The stack overflow issue related to Status..ctor(int) has been fixed in version **1.0.3**. You can now update to the latest version on NuGet, and everything should work as expected.

Appreciate your help in identifying these issues — feel free to reach out if you notice anything else!
